In [2]:
import pandas as pd

In [3]:
movies_metadata_path = 'C:/Users/Mia/Desktop/FINKI/WBS/wbs/data/movies_metadata.csv'
ratings_small_path = 'C:/Users/Mia/Desktop/FINKI/WBS/wbs/data/ratings_small.csv'

In [4]:
movies = pd.read_csv(movies_metadata_path)
ratings = pd.read_csv(ratings_small_path)

In [5]:
movies[:5]

,id,adult,budget,genres,original_language,title,overview,popularity,production_companies,production_countries,revenue,runtime,vote_average,vote_count
0,862,FALSE,30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",373554033.0,81.0,7.7,5415.0
1,8844,FALSE,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",262797249.0,104.0,6.9,2413.0
2,15602,FALSE,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",0.0,101.0,6.5,92.0
3,31357,FALSE,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",81452156.0,127.0,6.1,34.0
4,11862,FALSE,0,"[{'id': 35, 'name': 'Comedy'}]",en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",76578911.0,106.0,5.7,173.0

In [6]:
ratings[:5]

   userId  movieId  rating
0       1       31     2.5
1       1     1029     3.0
2       1     1061     3.0
3       1     1129     2.0
4       1     1172     4.0

In [7]:
ratings.rename(columns={'movieId': 'id'}, inplace=True)

In [14]:
movies['id'] = pd.to_numeric(movies['id'], errors='coerce')
movies = movies.dropna(subset=['id']).astype({'id': int})

In [15]:
movies['id']

0           862
1          8844
2         15602
3         31357
4         11862
          ...
45461    439050
45462    111109
45463     67758
45464    227506
45465    461257
Name: id, Length: 45463, dtype: int32

In [16]:
df = pd.merge(movies, ratings, on='id', how='inner')

In [19]:
df[:5]

,id,adult,budget,genres,original_language,title,overview,popularity,production_companies,production_countries,revenue,runtime,vote_average,vote_count,userId,rating
0,949,FALSE,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",en,Heat,"Obsessive master thief, Neil McCauley leads a ...",17.924927,"[{'name': 'Regency Enterprises', 'id': 508}, {...","[{'iso_3166_1': 'US', 'name': 'United States o...",187436818.0,170.0,7.7,1886.0,23,3.5
1,949,FALSE,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",en,Heat,"Obsessive master thief, Neil McCauley leads a ...",17.924927,"[{'name': 'Regency Enterprises', 'id': 508}, {...","[{'iso_3166_1': 'US', 'name': 'United States o...",187436818.0,170.0,7.7,1886.0,102,4.0
2,949,FALSE,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",en,Heat,"Obsessive master thief, Neil McCauley leads a ...",17.924927,"[{'name': 'Regency Enterprises', 'id': 508}, {...","[{'iso_3166_1': 'US', 'name': 'United States o...",187436818.0,170.0,7.7,1886.0,232,2.0
3,949,FALSE,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",en,Heat,"Obsessive master thief, Neil McCauley leads a ...",17.924927,"[{'name': 'Regency Enterprises', 'id': 508}, {...","[{'iso_3166_1': 'US', 'name': 'United States o...",187436818.0,170.0,7.7,1886.0,242,5.0
4,949,FALSE,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",en,Heat,"Obsessive master thief, Neil McCauley leads a ...",17.924927,"[{'name': 'Regency Enterprises', 'id': 508}, {...","[{'iso_3166_1': 'US', 'name': 'United States o...",187436818.0,170.0,7.7,1886.0,263,3.0

# Generating triplets using REBEL

In [20]:
!pip install transformers[torch] sentence-transformers

Requirement already satisfied: transformers[torch] in c:\users\mia\anaconda3\lib\site-packages (4.32.1)
Requirement already satisfied: sentence-transformers in c:\users\mia\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: filelock in c:\users\mia\anaconda3\lib\site-packages (from transformers[torch]) (3.9.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.15.1 in c:\users\mia\anaconda3\lib\site-packages (from transformers[torch]) (0.15.1)
Requirement already satisfied: numpy>=1.17 in c:\users\mia\anaconda3\lib\site-packages (from transformers[torch]) (1.24.3)
Requirement already satisfied: packaging>=20.0 in c:\users\mia\anaconda3\lib\site-packages (from transformers[torch]) (23.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\mia\anaconda3\lib\site-packages (from transformers[torch]) (6.0)
Requirement already satisfied: regex!=2019.12.17 in c:\users\mia\anaconda3\lib\site-packages (from transformers[torch]) (2022.7.9)
Requirement already satisfied: requests in c:\users\mia\anaconda3\lib\site-packages (from transformers[torch]) (2.31.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in c:\users\mia\anaconda3\lib\site-packages (from transformers[torch]) (0.13.2)
Requirement already satisfied: safetensors>=0.3.1 in c:\users\mia\anaconda3\lib\site-packages (from transformers[torch]) (0.3.2)
Requirement already satisfied: tqdm>=4.27 in c:\users\mia\anaconda3\lib\site-packages (from transformers[torch]) (4.65.0)
Requirement already satisfied: torch!=1.12.0,>=1.9 in c:\users\mia\anaconda3\lib\site-packages (from transformers[torch]) (2.1.0+cu118)
Collecting accelerate>=0.20.3 (from transformers[torch])
  Obtaining dependency information for accelerate>=0.20.3 from https://files.pythonhosted.org/packages/f7/fc/c55e5a2da345c9a24aa2e1e0f60eb2ca290b6a41be82da03a6d4baec4f99/accelerate-0.25.0-py3-none-any.whl.metadata
  Downloading accelerate-0.25.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: torchvision in c:\users\mia\anaconda3\lib\site-packages (from sentence-transformers) (0.16.0+cu118)
Requirement already satisfied: scikit-learn in c:\users\mia\anaconda3\lib\site-packages (from sentence-transformers) (1.3.0)
Requirement already satisfied: scipy in c:\users\mia\anaconda3\lib\site-packages (from sentence-transformers) (1.11.1)
Requirement already satisfied: nltk in c:\users\mia\anaconda3\lib\site-packages (from sentence-transformers) (3.8.1)
Requirement already satisfied: sentencepiece in c:\users\mia\anaconda3\lib\site-packages (from sentence-transformers) (0.1.99)
Requirement already satisfied: psutil in c:\users\mia\anaconda3\lib\site-packages (from accelerate>=0.20.3->transformers[torch]) (5.9.0)
Requirement already satisfied: fsspec in c:\users\mia\anaconda3\lib\site-packages (from huggingface-hub<1.0,>=0.15.1->transformers[torch]) (2023.4.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\mia\anaconda3\lib\site-packages (from huggingface-hub<1.0,>=0.15.1->transformers[torch]) (4.7.1)
Requirement already satisfied: sympy in c:\users\mia\anaconda3\lib\site-packages (from torch!=1.12.0,>=1.9->transformers[torch]) (1.11.1)
Requirement already satisfied: networkx in c:\users\mia\anaconda3\lib\site-packages (from torch!=1.12.0,>=1.9->transformers[torch]) (3.1)
Requirement already satisfied: jinja2 in c:\users\mia\anaconda3\lib\site-packages (from torch!=1.12.0,>=1.9->transformers[torch]) (3.1.2)
Requirement already satisfied: colorama in c:\users\mia\anaconda3\lib\site-packages (from tqdm>=4.27->transformers[torch]) (0.4.6)
Requirement already satisfied: click in c:\users\mia\anaconda3\lib\site-packages (from nltk->sentence-transformers) (8.0.4)
Requirement already satisfied: joblib in c:\users\mia\anaconda3\lib\site-packages (from nltk->sentence-transformers) (1.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\mia\anaconda3\lib\site-packages (from requests->transformers[torch]) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mia\anaconda3\lib\site-packages (from requests->transformers[torch]) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mia\anaconda3\lib\site-packages (from requests->transformers[torch]) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mia\anaconda3\lib\site-packages (from requests->transformers[torch]) (2023.7.22)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\mia\anaconda3\lib\site-packages (from scikit-learn->sentence-transformers) (2.2.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\mia\anaconda3\lib\site-packages (from torchvision->sentence-transformers) (9.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\mia\anaconda3\lib\site-packages (from jinja2->torch!=1.12.0,>=1.9->transformers[torch]) (2.1.1)
Requirement already satisfied: mpmath>=0.19 in c:\users\mia\anaconda3\lib\site-packages (from sympy->torch!=1.12.0,>=1.9->transformers[torch]) (1.3.0)
Downloading accelerate-0.25.0-py3-none-any.whl (265 kB)
   ---------------------------------------- 0.0/265.7 kB ? eta -:--:--
   - -------------------------------------- 10.2/265.7 kB ? eta -:--:--
   - -------------------------------------- 10.2/265.7 kB ? eta -:--:--
   ---- ---------------------------------- 30.7/265.7 kB 262.6 kB/s eta 0:00:01
   ---------- ---------------------------- 71.7/265.7 kB 435.7 kB/s eta 0:00:01
   --------------------------------- ------ 225.3/265.7 kB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 265.7/265.7 kB 1.1 MB/s eta 0:00:00
Installing collected packages: accelerate
Successfully installed accelerate-0.25.0

In [21]:
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
from sentence_transformers import SentenceTransformer, util
import torch
import pandas as pd
from tqdm import tqdm
import networkx as nx
from networkx import connected_components
import matplotlib.pyplot as plt
import random

Matplotlib is building the font cache; this may take a moment.

In [22]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [23]:
def extract_triplets_typed(text):
    triplets = []
    relation = ''
    text = text.strip()
    current = 'x'
    subject, relation, object_, object_type, subject_type = '','','','',''

    for token in text.replace("<s>", "").replace("<pad>", "").replace("</s>", "").replace("tp_XX", "").replace("__en__", "").split():
        if token == "<triplet>" or token == "<relation>":
            current = 't'
            if relation != '':
                triplets.append({'head': subject.strip(), 'head_type': subject_type, 'type': relation.strip(),'tail': object_.strip(), 'tail_type': object_type})
                relation = ''
            subject = ''
        elif token.startswith("<") and token.endswith(">"):
            if current == 't' or current == 'o':
                current = 's'
                if relation != '':
                    triplets.append({'head': subject.strip(), 'head_type': subject_type, 'type': relation.strip(),'tail': object_.strip(), 'tail_type': object_type})
                object_ = ''
                subject_type = token[1:-1]
            else:
                current = 'o'
                object_type = token[1:-1]
                relation = ''
        else:
            if current == 't':
                subject += ' ' + token
            elif current == 's':
                object_ += ' ' + token
            elif current == 'o':
                relation += ' ' + token
    if subject != '' and relation != '' and object_ != '' and object_type != '' and subject_type != '':
        triplets.append({'head': subject.strip(), 'head_type': subject_type, 'type': relation.strip(),'tail': object_.strip(), 'tail_type': object_type})
    return triplets

In [24]:
def tokenize_and_extract_relations(text):
  # Tokenizer text

  gen_kwargs = {
    "max_length": 256,
    "length_penalty": 0,
    "num_beams": 3,
    "num_return_sequences": 3,
  }

  model_inputs = tokenizer(text, max_length=256, padding=True, truncation=True, return_tensors = 'pt')  # tokenize the input and return pytorch tensors

  # Generate

  # The model input contains the 'input_ids' (the ids of the inpu tokens)
  # and 'attention_mask' a mask that shows the model which tokens are important and which are not.
  generated_tokens = model.generate(
    model_inputs["input_ids"].to(model.device),
    attention_mask=model_inputs["attention_mask"].to(model.device),
    decoder_start_token_id = tokenizer.convert_tokens_to_ids("tp_XX"),  # these decodes the tokens to ids using triples as the target 'language'
    **gen_kwargs,
  )

  # Extract text
  decoded_preds = tokenizer.batch_decode(generated_tokens, skip_special_tokens=False)

  # Extract triplets using the utility function (the generation returns 3 triples)
  result = []
  for idx, sentence in enumerate(decoded_preds):
    result.extend(extract_triplets_typed(sentence))
  return result

In [25]:
# Load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("Babelscape/mrebel-large", src_lang="en_XX", tgt_lang="tp_XX")
# Here we set English ("en_XX") as source language. To change the source language swap the first token of the input for your desired language or change to supported language. For catalan ("ca_XX") or greek ("el_EL") (not included in mBART pretraining) you need a workaround:
# tokenizer._src_lang = "ca_XX"
# tokenizer.cur_lang_code_id = tokenizer.convert_tokens_to_ids("ca_XX")
# tokenizer.set_src_lang_special_tokens("ca_XX")
model = AutoModelForSeq2SeqLM.from_pretrained("Babelscape/mrebel-large")

Downloading tokenizer_config.json:   0%|          | 0.00/1.28k [00:00<?, ?B/s]

Downloading (…)tencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

Downloading tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

Downloading added_tokens.json:   0%|          | 0.00/307 [00:00<?, ?B/s]

Downloading (…)cial_tokens_map.json:   0%|          | 0.00/829 [00:00<?, ?B/s]

Downloading config.json:   0%|          | 0.00/1.42k [00:00<?, ?B/s]

Downloading model.safetensors:   0%|          | 0.00/2.44G [00:00<?, ?B/s]

In [26]:
model.to(device)

MBartForConditionalGeneration(
  (model): MBartModel(
    (shared): Embedding(250071, 1024, padding_idx=1)
    (encoder): MBartEncoder(
      (embed_tokens): Embedding(250071, 1024, padding_idx=1)
      (embed_positions): MBartLearnedPositionalEmbedding(1026, 1024)
      (layers): ModuleList(
        (0-11): 12 x MBartEncoderLayer(
          (self_attn): MBartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (activation_fn): GELUActivation()
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layernorm_embedding): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
    (decoder): MBartDecoder(
      (embed_tokens): Embedding(250071, 1024, padding_idx=1)
      (embed_positions): MBartLearnedPositionalEmbedding(1026, 1024)
      (layers): ModuleList(
        (0-11): 12 x MBartDecoderLayer(
          (self_attn): MBartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (activation_fn): GELUActivation()
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (encoder_attn): MBartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (encoder_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layernorm_embedding): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
  )
  (lm_head): Linear(in_features=1024, out_features=250071, bias=False)
)

# Creating sentences

In [27]:
df[:2]

,id,adult,budget,genres,original_language,title,overview,popularity,production_companies,production_countries,revenue,runtime,vote_average,vote_count,userId,rating
0,949,FALSE,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",en,Heat,"Obsessive master thief, Neil McCauley leads a ...",17.924927,"[{'name': 'Regency Enterprises', 'id': 508}, {...","[{'iso_3166_1': 'US', 'name': 'United States o...",187436818.0,170.0,7.7,1886.0,23,3.5
1,949,FALSE,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",en,Heat,"Obsessive master thief, Neil McCauley leads a ...",17.924927,"[{'name': 'Regency Enterprises', 'id': 508}, {...","[{'iso_3166_1': 'US', 'name': 'United States o...",187436818.0,170.0,7.7,1886.0,102,4.0

In [28]:
df['Sentence'] = df.apply(lambda row: f"{row['title']} ({row['original_language']}), has a runtime of {row['runtime']} and revenue of {row['revenue']}$. Overview: {row['overview']}. User {row['userId']} rated {row['title']} {row['rating']} stars.", axis=1)

In [31]:
kg = []
for content in tqdm(df['Sentence'].values[:100]):
  kg.extend(tokenize_and_extract_relations(content))

100%|██████████| 100/100 [07:06<00:00,  4.27s/it]

In [32]:
kg_relations = pd.DataFrame(kg)

In [33]:
kg_relations = kg_relations.dropna()  # drop possible null values

In [34]:
kg_relations = kg_relations.drop_duplicates(subset=['head', 'type', 'tail'], keep='first')

In [35]:
kg_relations

,head,head_type,type,tail,tail_type
0,Neil McCauley,per,occupation,thief,concept
1,Neil McCauley,media,residence,Los Angeles,loc
2,Heat,media,cast member,Neil McCauley,per
5,Heat,media,creator,Neil McCauley,per
27,Heat,media,narrative location,Los Angeles,loc
29,Heat,media,characters,Neil McCauley,media
45,Heat,media,cast member,Vincent Hanna,per
49,GoldenEye,media,characters,James Bond,org
50,GoldenEye,media,country of origin,Britain,loc
51,GoldenEye,media,characters,Janus Syndicate,media
55,Cutthroat Island,media,characters,Morgan Adams,media
57,Cutthroat Island,media,characters,William Shaw,media
63,Cutthroat Island,media,performer,Morgan Adams,per
184,Morgan Adams,media,unmarried partner,William Shaw,media
185,William Shaw,media,unmarried partner,Morgan Adams,media
264,Casino,media,main subject,Las Vegas,loc
265,Casino,media,located in the administrative territorial entity,Las Vegas,loc
266,Casino,media,headquarters location,Las Vegas,loc
270,Casino,concept,use,gambling,concept
274,Casino,media,main subject,gambling,concept
372,Sense and Sensibility,media,characters,Rich Mr. Dashwood,media
375,Four Rooms,media,characters,Ted the Bellhop,media
376,Four Rooms,media,cast member,Ted the Bellhop,per
377,Four Rooms,media,performer,Ted the Bellhop,per

In [36]:
import networkx as nx
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

In [37]:
graph = nx.Graph()

In [39]:
for index, row in movies.iterrows():
    movie_id = row['id']
    graph.add_node(movie_id, label='movie', attributes=row.to_dict())

In [40]:
for user_id in ratings['userId'].unique():
    graph.add_node(user_id, label='user')

In [42]:
for index, row in ratings.iterrows():
    user_id = row['userId']
    movie_id = row['id']
    rating = row['rating']

    if rating >= 3:
        graph.add_edge(user_id, movie_id, label='rated')

In [49]:
movie_titles = movies['title'].dropna().tolist()
tfidf_vectorizer = TfidfVectorizer()
movie_title_embeddings = tfidf_vectorizer.fit_transform(movie_titles).toarray()

In [50]:
def resolve_entities_by_text_embeddings(entities, embeddings):
    entity_mapping = {}
    for i in range(len(entities)):
        e1 = entities[i]
        for j in range(i + 1, len(entities)):
            e2 = entities[j]

            if e1 == e2:
                continue

            similarity = cosine_similarity([embeddings[i]], [embeddings[j]])[0][0]

            if similarity > 0.95:
                entity_mapping[entities[j]] = entities[i]
                entities[j] = entities[i]
                embeddings[j] = embeddings[i]

    return entity_mapping

In [51]:
entity_mapping = resolve_entities_by_text_embeddings(movie_titles, movie_title_embeddings)

In [ ]:
for old_title, new_title in entity_mapping.items():
    old_movie_id = movies[movies['title'] == old_title]['id'].iloc[0]
    new_movie_id = movies[movies['title'] == new_title]['id'].iloc[0]
    
    user_nodes = [node for node, label in graph.nodes(data='label') if label == 'user']
    for user_node in user_nodes:
        rating = ratings[(ratings['userId'] == user_node) & (ratings['movieId'] == old_movie_id)]['rating'].values
        if len(rating) > 0 and rating[0] >= 3:
            graph.add_edge(user_node, new_movie_id, label='rated')